conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),

]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.user_logout, name='user_logout'),
]
    

item/urls.py
from django.urls import path

from . import views

app_name = "item"

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/delete', views.delete, name="delete"),
    path('<int:pk>/edit', views.edit, name="edit"),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)


    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__ (self):
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at =models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return self.name

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category', 'name', 'description', 'price', 'image']
        widgets = {
        'category': forms.Select(attrs={
            'class': INPUT_CLASSES 
        }),
        'name': forms.TextInput(attrs={
        'class': INPUT_CLASSES 
        }),
        'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES 
        }),
        'price': forms.TextInput(attrs={
        'class': INPUT_CLASSES 
        }),
        'image': forms.FileInput(attrs={
        'class': INPUT_CLASSES 
        }),
    }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image', 'is_sold']
        widgets = {
        'name': forms.TextInput(attrs={
        'class': INPUT_CLASSES 
        }),
        'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES 
        }),
        'price': forms.TextInput(attrs={
        'class': INPUT_CLASSES 
        }),
        'image': forms.FileInput(attrs={
        'class': INPUT_CLASSES 
        }),
    }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .  forms import NewItemForm, EditItemForm
from .models import Item, Category

def items(request):
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)

    if query:
        items = items.filter(Q (name__icontains=query) | Q (description__icontains=query))
    
    if category_id:
        items = items.filter(category_id=category_id)

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories':categories,
        'category_id':int(category_id)
    })


# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    
    return render(request, 'item/detail.html', {
        'item' : item,
        'related_items': related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form':form,
        'title': 'New Item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()

    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form':form,
        'title': 'Edit Item',
    })

item/templates/item/detail.html
{% extends 'core/base.html' %} {% block title %}{{ item.name }}{% endblock %} 
{% block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    <img src="{{ item.image.url }}" class="rounded-xl" />
  </div>

  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
    <p class="text-gray-500">
      <strong>Seller: </strong>{{ item.created_by.username}}
    </p>

    {% if item.description %}
    <p class="text-gray-700">
      <strong class="text-gray-500">Description: </strong><br />
      {{ item.description }}
    </p>
    {% endif %}

    {% if request.user == item.created_by %}
    <div class="mt-6 p-6 bg-white rounded-xl">
      <p>This is your item!</p>
      <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
      <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
    </div>
    {% else %}
    <a
      href="{% url 'conversation:new' item.id %}"
      class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
      >Contact Seller</a
    >
    {% endif %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Related Items</h2>

  <div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
    <div>
      <a href="{% url 'item:detail' item.id %}">
        <div>
          <img src="{{ item.image.url }}" class="rounded-t-xl" />
        </div>

        <div class="p-6 bg-white rounded-b-xl">
          <h2 class="text-2xl">{{ item.name }}</h2>
          <p class="text-gray-500">Price : {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}
   
{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}

        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{  form_non_field_errors }}
        </div>

    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit<button>
</form>


{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %} 
{% block title %}Items{% endblock %} 
{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4">
  <div class="col-span-1">
    <form method="get" action="{% url 'item:items' %}">
      <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{  query }}"
      placeholder="Find what you want..">

      <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
    </form>

    <hr class="my-6">

    <p class="font-semibold">Categories</p>

    <ul>
      {% for category in categories %}
      <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
      </li>
        {% endfor %}
    </ul>

    <hr class="my-6">

    <p class="font-semibold">Clear filters</p>
    <ul>
      <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Reset</a>
      </li> 
    </ul>
  </div>

  <div class="col-span-3">
    <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
      <div>
        <a href="{% url 'item:detail' item.id %}">
          <div>
            <img src="{{ item.image.url }}" class="rounded-t-xl" />
          </div>

          <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{ item.name }}</h2>
            <p class="text-gray-500">Price : {{ item.price }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>

  {% endblock %}